// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcuxrdinypfdsntqouwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdXhyZGlueXBmZHNudHFvdXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjY3NjgsImV4cCI6MjA3MjA0Mjc2OH0.Fcq8IXeX-Q3IMw6k3gouBOhXu5DuB3IL8Rpy87crqQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});